# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)


pet = Pet.create(name:"Dog")
pet2 = Pet.create(name:"Cat")
pet3 = Pet.create(name:"Hamster")
# pet4 = Pet.create(name:"Fish")
# pet5 = Pet.create(name:"Lizards")
# pet6 = Pet.create(name:"Snakes")
# pet7 = Pet.create(name:"Bunny")
# pet8 = Pet.create(name:"Mice and Rats")
# pet9 = Pet.create(name:"Spiders & Tarantula")
# pet10 = Pet.create(name:"Bird")

pet.items.create(name:"Food", description:"Healthy, chicken", price:58.00)
pet.items.create(name:"Toy", description:"Safe", price:15.00)
pet.items.create(name:"Collars and Leashes", description:"Fancy Gold collar", price:12.50)
pet2.items.create(name:"Food", description:"Healthy", price:35.00)
pet2.items.create(name:"Toy", description:"Plastic", price:10.00)
pet2.items.create(name:"Collars", description:"Fancy collar", price:14.78)
pet3.items.create(name:"Cage", description:"Steel and safe", price:70.00)
pet3.items.create(name:"Toys", description:"Plastic", price:10.00)
pet3.items.create(name:"Food", description:"Healthy", price:20.00)
pet4.items.create(name:"Cage", description:"Steel and safe", price:70.00)
pet4.items.create(name:"Toys", description:"Plastic", price:10.00)
pet4.items.create(name:"Food", description:"Healthy", price:20.00)
pet5.items.create(name:"Cage", description:"Steel and safe", price:70.00)
pet5.items.create(name:"Toys", description:"Plastic", price:10.00)
pet5.items.create(name:"Food", description:"Healthy", price:20.00)
pet6.items.create(name:"Cage", description:"Steel and safe", price:70.00)
pet6.items.create(name:"Toys", description:"Plastic", price:10.00)
pet6.items.create(name:"Food", description:"Healthy", price:20.00)
pet7.items.create(name:"Cage", description:"Steel and safe", price:70.00)
pet7.items.create(name:"Toys", description:"Plastic", price:10.00)
pet7.items.create(name:"Food", description:"Healthy", price:20.00)
pet8.items.create(name:"Cage", description:"Steel and safe", price:70.00)
pet8.items.create(name:"Toys", description:"Plastic", price:10.00)
pet8.items.create(name:"Food", description:"Healthy", price:20.00)
pet9.items.create(name:"Cages", description:"Glass", price:70.00)
pet9.items.create(name:"Toys", description:"Plastic", price:10.00)
pet9.items.create(name:"Food", description:"Buggy", price:20.00)
pet10.items.create(name:"Cage", description:"Steel and safe", price:70.00)
pet10.items.create(name:"Toys", description:"Plastic", price:10.00)
pet10.items.create(name:"Food", description:"Healthy", price:20.00)

job = Job.create(title:"Name Brand Groomer", company:"RMS", salary:100000)
job2 = Job.create(title:"Sitter", company:"RMS", salary:30000)
job3 = Job.create(title:"Cat Trainer", company:"RMS", salary:55000)
# job4 = Job.create(title:"Dog Trainer", company:"RMS", salary:55000)
# job5 = Job.create(title:"Falcon Trainer", company:"RMS", salary:55000)
# job6 = Job.create(title:"Dog Walker", company:"RMS", salary:55000)
# job7 = Job.create(title:"Pet Daycare Manager", company:"RMS", salary:55000)
# job8 = Job.create(title:"Pet Daycare assistant", company:"RMS", salary:55000)
# job9 = Job.create(title:"Janitorial staff", company:"RMS", salary:55000)
# job10 = Job.create(title:"Sales Clerk", company:"RMS", salary:55000)